on: push
name: Tests / test-org-mirror
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
    - name: Mirror Github to Gitee
      uses: ./.
      with:
        src: github/violet-mio #源端账户名
        dst: gitee/violet-mio #目的端账户名
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        # Only sync normal repo
        white_list: 'my-vue2-admin,my-newbee-admin,my-vue3-adminy'
        force_update: true
        debug: true

